### ISSUE TITLE
Reflective xss vulnerability

### ISSUE THREAD

**Issue by 360CodeSafe** [SAP/cloud-s4-sdk-book#21]
Hello:
I am a member of the 360 ​​Code Safe team. In our open source code detection project, I found a reflective xss vulnerability in "cloud-s4-sdk-book". The details are as follows:
In the 31st line of BusinessPartnerServlet.java, the parameter "id" in the request is received. When the parameter is invalid (length is greater than 10), an error message will be displayed on the page, and the id parameter is inserted in the error message. A malicious attacker can perform an xss attack by constructing a parameter id.
![图片](https://user-images.githubusercontent.com/39950310/54899466-dd257e80-4f0a-11e9-8bf8-908a4f72d16a.png)

**Comment by sacnl** [comment]
Thanks for reporting this. This is fixed in master and will soon be fixed in other branches as well.
