### ISSUE TITLE
Error 403 when trying to add address

### ISSUE THREAD

**Issue by lamcharfi** [SAP/cloud-s4-sdk-book#31]
Hello,

I just clone this repository and checkout the course/2_2_start branch, start the local mock-server, set the destination variable and start the application.

I am facing an issue when I try to add a new address. My browser return : 
- a 403 http code for POST http://localhost:8080/api/addresses 403 (forbidden)
- a 405 http code for GET http://localhost:8080/api/addresses 405 (not allowed method)
=> no new address has been created.

Is there any additional configuration to do ?

Regards,
Amine

**Comment by sacnl** [comment]
Hello Amine,

most likely you are not sending a CSRF token with the POST request. The API is protected by a CSRF filter - see https://github.com/SAP/cloud-s4-sdk-book/blob/course/2_2_start/application/src/main/webapp/WEB-INF/web.xml#L29

You first have to fetch a CSRF token and then send it as part of the request. For example, see https://answers.sap.com/questions/12196581/x-csrf-token.html

The 405 on /api/addresses is expected, as no method for handling GET requests has been implemented for that endpoint.

Best regards

**Comment by lamcharfi** [comment]
Thanks !
